default: &default
  adapter: postgresql
  encoding: unicode 
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  adapter: postgresql
  database: rubyBlog_dev
  username: peperoncino
  encoding: unicode
  host: localhost
  pool: 5
  
test:
  adapter: postgresql
  database: rubyBlog_test
  username: peperoncino
  encoding: unicode
  host: localhost
  pool: 5

production:
  <<: *default
  database: rubyBlog_production
  username: peperoncino
  password: 
